global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hello-service'
    metrics_path: '/api/v1/hello/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['hello-service:8081']

  - job_name: 'world-service'
    metrics_path: '/api/v1/world/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['world-service:8082']

  - job_name: 'hello-world-aggregator'
    metrics_path: '/api/v1/hello-world/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['hello-world-aggregator:8080']
